// Properties used internally by protobufjs on Namespace/ReflectionObject instances.
// A protobuf package component that happens to share one of these names must not be
// promoted to a direct property, or it would corrupt protobufjs's internal state.
// (Such types are still reachable via root.lookup() or root.nested traversal.)
const ROOT_PROPS = new Set([
  'options',
  'parsedOptions',
  'name',
  'parent',
  'resolved',
  'comment',
  'filename',
  'nested',
  '_nestedArray',
]);
const PATCHED_STATIC_SERVICE = Symbol('temporalPatchedStaticService');

/**
 * Create a version of `root` with non-nested namespaces to match the generated types.
 * For more information, see:
 * https://github.com/temporalio/sdk-typescript/blob/main/docs/protobuf-libraries.md#current-solution
 * @param root Generated by `pbjs -t static-module -w commonjs -o static-module.js *.proto` or a legacy
 * protobufjs reflection root.
 * @returns A new patched `root`
 */
export function patchProtobufRoot<T extends Record<string, unknown>>(root: T): T {
  if (!isRecord(root.nested) && !isNamespace(root) && !isType(root)) {
    return patchStaticProtobufRoot(root);
  }

  const patched = _patchProtobufRoot(root);

  // Protobufjs >=7.5.2 added a fast-path cache in Namespace#lookup() that accesses
  // `this.root._fullyQualifiedObjects`. The `root` accessor is defined as a non-enumerable
  // getter on `ReflectionObject.prototype`, so it is not copied by `for...in` loops.
  // When the patched root is imported via `import * as proto from '@temporalio/proto'`,
  // TypeScript's `__importStar` helper wraps the CJS module in a plain object by iterating
  // own enumerable properties with `for...in` + `hasOwnProperty`. Because `root` is
  // non-enumerable, it is skipped, the wrapper's `root` is `undefined`, and any subsequent
  // `this.root._fullyQualifiedObjects` access crashes.
  // Defining `root` as an own **enumerable** getter ensures `__importStar` includes it in
  // the wrapper, so that `wrapper.root` delegates back to the patched root (which has the
  // proper `_fullyQualifiedObjects` map and full prototype chain).
  if (!Object.getOwnPropertyDescriptor(patched, 'root')) {
    Object.defineProperty(patched, 'root', {
      get(this: any) {
        // eslint-disable-next-line @typescript-eslint/no-this-alias
        let ptr = this;
        while (ptr.parent !== null) ptr = ptr.parent;
        return ptr;
      },
      enumerable: true,
      configurable: true,
    });
  }

  return patched;
}

function patchStaticProtobufRoot<T extends Record<string, unknown>>(root: T): T {
  const registry = new Map<string, unknown>();
  indexStaticNamespace(registry, root);

  if (!Object.getOwnPropertyDescriptor(root, 'root')) {
    Object.defineProperty(root, 'root', {
      get() {
        return root;
      },
      enumerable: true,
      configurable: true,
    });
  }

  if (!Object.getOwnPropertyDescriptor(root, 'lookup')) {
    Object.defineProperty(root, 'lookup', {
      value(path: string | string[]) {
        const normalizedPath = normalizeLookupPath(path);
        const value = registry.get(normalizedPath);
        if (value === undefined) {
          throw new Error(`no such type: ${normalizedPath}`);
        }
        return value;
      },
      enumerable: true,
      configurable: true,
    });
  }

  if (!Object.getOwnPropertyDescriptor(root, 'lookupType')) {
    Object.defineProperty(root, 'lookupType', {
      value(path: string | string[]) {
        const normalizedPath = normalizeLookupPath(path);
        const value = registry.get(normalizedPath);
        if (!isStaticMessageType(value)) {
          throw new Error(`no such type: ${normalizedPath}`);
        }
        return value;
      },
      enumerable: true,
      configurable: true,
    });
  }

  if (!Object.getOwnPropertyDescriptor(root, 'lookupService')) {
    Object.defineProperty(root, 'lookupService', {
      value(path: string | string[]) {
        const normalizedPath = normalizeLookupPath(path);
        const value = registry.get(normalizedPath);
        if (!isStaticService(value)) {
          throw new Error(`no such service: ${normalizedPath}`);
        }
        return value;
      },
      enumerable: true,
      configurable: true,
    });
  }

  return root;
}

function _patchProtobufRoot<T extends Record<string, unknown>>(root: T, name?: string): T {
  const newRoot = new (root.constructor as any)(isNamespace(root) ? name : {});
  for (const key in root) {
    // 'root' is a getter-only accessor defined on ReflectionObject.prototype. Trying to
    // assign it as a plain property on a new Root/Namespace instance throws in strict mode.
    // It is also safe to skip because each object correctly resolves its own root at runtime
    // by traversing the parent chain. The top-level own enumerable getter is added separately
    // by patchProtobufRoot() after recursion completes.
    if (key === 'root') continue;
    newRoot[key] = root[key];
  }

  if (isRecord(root.nested)) {
    for (const typeOrNamespace in root.nested) {
      // Skip names that protobufjs uses internally — overriding them would corrupt
      // the namespace object's internal state. Types/namespaces with these names are
      // still reachable via root.lookup() or by traversing root.nested manually.
      if (ROOT_PROPS.has(typeOrNamespace)) continue;

      const value = root.nested[typeOrNamespace];
      if (isNamespace(value)) {
        newRoot[typeOrNamespace] = _patchProtobufRoot(value, typeOrNamespace);
      } else if (isType(value)) {
        newRoot[typeOrNamespace] = value;
      }
    }
  }

  return newRoot;
}

type Type = Record<string, unknown>;
type Namespace = { nested: Record<string, unknown> };

function isType(value: unknown): value is Type {
  // constructor.name may get mangled by minifiers; thankfully protobufjs also sets a constructor.className property
  return isRecord(value) && (value.constructor as any).className === 'Type';
}

function isNamespace(value: unknown): value is Namespace {
  // constructor.name may get mangled by minifiers; thankfully protobufjs also sets a constructor.className property
  return isRecord(value) && (value.constructor as any).className === 'Namespace';
}

function isStaticMessageType(value: unknown): boolean {
  return (
    typeof value === 'function' &&
    typeof (value as any).create === 'function' &&
    typeof (value as any).encode === 'function' &&
    typeof (value as any).decode === 'function' &&
    typeof (value as any).fromObject === 'function' &&
    typeof (value as any).toObject === 'function'
  );
}

function isStaticService(value: unknown): boolean {
  return (
    typeof value === 'function' &&
    typeof (value as any).create === 'function' &&
    !isStaticMessageType(value) &&
    isRecord((value as any).prototype)
  );
}

function indexStaticNamespace(registry: Map<string, unknown>, value: unknown, path: string[] = []): void {
  if (!isRecord(value)) return;

  if (path.length > 0) {
    registry.set(path.join('.'), value);
  }

  for (const [key, child] of Object.entries(value)) {
    if (key === 'root' || key === 'lookup' || key === 'lookupType' || key === 'lookupService') continue;

    const childPath = [...path, key];
    if (isStaticMessageType(child) || isStaticService(child)) {
      if (isStaticService(child)) {
        patchStaticService(child);
      }
      registry.set(childPath.join('.'), child);
    } else if (isRecord(child)) {
      indexStaticNamespace(registry, child, childPath);
    }
  }
}

function normalizeLookupPath(path: string | string[]): string {
  return (Array.isArray(path) ? path.join('.') : path).replace(/^\./, '');
}

function patchStaticService(value: unknown): void {
  const service = value as {
    create: (...args: unknown[]) => unknown;
    prototype: Record<string, unknown>;
    [PATCHED_STATIC_SERVICE]?: boolean;
  };
  if (service[PATCHED_STATIC_SERVICE]) return;

  const originalCreate = service.create;
  Object.defineProperty(service, 'create', {
    value(this: unknown, ...args: unknown[]) {
      const instance = originalCreate.apply(this, args) as Record<string, unknown>;
      for (const methodName of Object.keys(service.prototype)) {
        const method = instance[methodName];
        if (typeof method === 'function' && !Object.prototype.propertyIsEnumerable.call(instance, methodName)) {
          Object.defineProperty(instance, methodName, {
            value: method.bind(instance),
            enumerable: true,
            configurable: true,
            writable: true,
          });
        }
      }
      return instance;
    },
    enumerable: true,
    configurable: true,
    writable: true,
  });
  Object.defineProperty(service, PATCHED_STATIC_SERVICE, { value: true });
}

// Duplicate from type-helpers instead of importing in order to avoid circular dependency
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
